// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: updateRFTokenRecord.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const updateRFToken = `-- name: UpdateRFToken :exec
UPDATE refresh_tokens
SET revoked_at = $1, updated_at = $2
WHERE token = $3
`

type UpdateRFTokenParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) UpdateRFToken(ctx context.Context, arg UpdateRFTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRFToken, arg.RevokedAt, arg.UpdatedAt, arg.Token)
	return err
}
